[build]
  publish = "public"  # Directory to publish static files (if any)
  functions = "functions" # Directory containing your Netlify Functions
  command = "pip install -r requirements.txt -t functions/api" # Install dependencies in function directory

[[redirects]]
  from = "/api/*"  # Route to trigger your Flask function
  to = "/.netlify/functions/api/:splat" # Netlify Function path
  status = 200      # Status code for the redirect