[build]
  publish = "public"
  functions = "functions"
  command = "pip install -r requirements.txt -t functions/api" # **Correct and Crucial Command**

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200